-- Schema for the `flight` table.
-- Owned by this script rather than by Hibernate (ddl-auto: validate), so the
-- route index below survives restarts. Both statements are idempotent.

CREATE TABLE IF NOT EXISTS flight (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(10)   NOT NULL,
    source        VARCHAR(3)    NOT NULL,
    destination   VARCHAR(3)    NOT NULL,
    airline       VARCHAR(50)   NOT NULL,
    price         NUMERIC(10,2) NOT NULL
);

-- Matches the UPPER(...) comparison generated by the repository's
-- findBySourceIgnoreCaseAndDestinationIgnoreCase... query.
CREATE INDEX IF NOT EXISTS idx_flight_route
    ON flight (UPPER(source), UPPER(destination));
